[build]
  publish = "."
  functions = "netlify/functions"

# Memastikan Netlify mengarahkan segala ralat URL kembali ke index.html (Penting untuk aplikasi SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
